#TODO ?????????
server:
  port: 80


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web1.0
    username: root
    password: 123456


#      jdbc.driverClassName=com.mysql.jdbc.Driver
#      jdbc.url=jdbc:mysql://localhost:3306/web1.0
#      #?serverTimezone=GMT&useSSL=false
#      jdbc.username=root
#      jdbc.password=123456


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#关闭实体类驼峰到数据库下划线的映射
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


